# Description: default configuration for PromptMR model, may vary for different datasets
# NOTE: we are trying to fit feature dims into a headdim of 48, so might need to adjust a lot
model:
  class_path: pl_modules.PromptMrModule
  init_args:
    num_cascades: 12
    num_adj_slices: 5
    n_feat0: 96
    feature_dim: [192,384,768]
    prompt_dim: [96,192,384]
    sens_n_feat0: 48
    sens_feature_dim: [96,192,384]
    sens_prompt_dim: [48,96,192]
    len_prompt: [5,5,5]
    prompt_size: [64,32,16]
    n_enc_cab: [2,2,2]
    n_dec_cab: [2,2,2]
    n_skip_cab: [1,1,1]
    n_bottleneck_cab: 4    
    no_use_ca: false
    learnable_prompt: false
    adaptive_input: false
    n_buffer: 0
    n_history: 0
    use_sens_adj: True
    lr_gamma: 0.1
    weight_decay: 1e-2
    use_checkpoint: true

# add model tags to wandb
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      tags: [promptmamba]
